title: Ethical Hacking Blog
author: Alvin Wainaina
description: >
  Welcome to my Ethical Hacking blog! 🚀  
  Here, I document my journey in cybersecurity, breaking down key hacking concepts, tools, and techniques.  
  From penetration testing to Linux security, my goal is to share knowledge, reinforce my learning, and help others dive into the world of ethical hacking.  
  Stay tuned for tutorials, walkthroughs, and hands-on experiments!  

theme: minima
css: styles.css
